language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install pytest
- pip install codecov
- pip install pytest-cov
script:
- py.test --cov=aruudy/poetry tests/*_u.py
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  on:
    python: '2.7'
  password:
    secure: H5btEwKXDcxnKPDB5cWLlN3UskQmJny21sGRkUR0Wdndh+aeL6oCKut59OZcMcmtfTXslwJ7RRlUndk2eLmcsLmIxzA3YDjCs3f3W8b3n5uf+hkjRf+WN6xovKBeYqy3EGpJdY+pJ+OfRfeojJWdFxZnF4NHvF5Qm0BTIyYMuORMbER4ihvGc+fe3v6qtRagvDrbZ/9eRgtMXDxwiMzgH8cfewYJ/epB6WvYJrOo5dlBVmQc1kOn1rlGHuPgsChcAKUqcDiwKx0XUL40E7qXOR49SNOEihPl3O3xdWFRUR+yMswYOh3O8YVZqJYtvl4Dp6P+TGD7CRrsq32+Q2tTz49RJyGcbcxp+tAzWY26wxMwJssOBUYtVCHtVcpTWLPjLmASQpBHxO9Tt7ewPb1CeqqfFis+ybdY+v9UmiMzsSIVCiIwR6ECmNQAZRHDoRmIPJPCQDqEndt0OEAT2cRzibXb9uwNDfqFOCQvvoAHFWYqYOWOD7u3EyIGDPedRdM39qkqdAHZLZ/Wf3XjW7M/L3GWCwAs0RULwI/99vdURgpbXpBoNNKg1wQc5c1qeCgbWZn2rnA25vDJ5B9Ag2hgmW3zZZhz33eDQA8NDI0Gd0yDICQ0SIaXPYme/gB0yULfn4z06/0qDheqM3ydOGgHSXfVuFF6MecW1H3ga1sjoT4=
