language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- pip install pytest
- pip install codecov
- pip install pytest-cov
script:
- py.test --cov=aruudy/poetry tests/*_u.py
after_success:
- codecov
deploy:
  provider: pypi
  user: __token__
  on:
    python: '3.6'
  password:
    secure: "RlwVneNqB04j1Z6qmddYNU5mxkEAsdgYTmhTIpqvWuTIPW/ebo9b0FI5G5QavQaxsmuCfGyTSvtOJVj421rga61KtgXzdcuQPS6PIH4fKo9WE2hQYjqBGm78Xk4u943vnjbLWrvVGywK3f1/GhEvk224HFNe7CWQh01lKYVx8EF8np+F5tKXLaY3JRcoR1q+WMVy7QjZ7vKcew1v0fwyhazUSTH+JnPHOtEPp/ua98GiawKDE8dc3yYY10/vpnnYdKolEsM/NpoBh9eM5p8gWUjFKAiiHKtRWciMWraiGAxbZ4TsD4ezFStFA/ngiG5YVRNJjq7+4VK2TrwBu9uR2Bo2I9UcdPnZCeV4AvDZ79N3mggcf2Q+2+F8iSpjEGmuYfqanG2/y2/gOHqTkdrlwN2akDZH/FdePbgxX6C9Hhbn/EW1MA5mycmjJYhna/F33/p8A5xkLSeVDmsQqyZg5uUZ0X5lStKd3nZl1HSQAMeMoNjADjselU2O7ir/TqHn895owdJqngnqp8S912UGMvGztWNqI2PdevulvG0DSB9m0DUyvGOHLnGfB2P02wLXd+QMrSZalxiuRSqeFnViqlzNv4+5D+KcDCuWbFS7h1laXLBspM5BvA9zAXjiZrWJBIx9xur/YddF6cwq8QVGt4fdoNnCYBJIhj4swHrgVbc="
